"number","attribute"
"1","Behavioral traits"
"2","Phenological traits"
"3","Life history traits"
"4","Other Species traits, e.g. morphological, physiological"
"5","Trait evolution = Evolution"
"6","Niche shift"
"7","Abundance / density"
"8","Community composition"
"9","Grouping : Species interactions"
"13","Phylogenetic distance"
"14","Functional novelty"
"15","Habitat quality"
"16","Ecosystem functioning and services"
"17","Grouping : Abiotic"
"25","Novel organisms"
"26","Novel community composition and structure (other than addition of novel organisms, e.g. change in predators)"
"27","Human presence & intervention = human interference = propagule pressure + other human actions"
"28","Propagule pressure"
"29","in general...60"
"30","Habitat modification"
"31","Resources"
"32","Other ecosystem properties"
"33","in general...64"